name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main
      - development
jobs:
  coverage:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '19'
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          test-script: npm run test:ci
